#!/bin/sh
#
# Starts Treadmill cgroup management service
# Runs as root.
#

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    service \
        --root-dir {{ dir }} \
    cgroup
