#!/bin/sh

# Script to start the synchronization job that updates the set of Treadmill
# nodes for use by the firewall.
# Runs as root with host principal creds.
#

# This service needs host tickets

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    firewall node_sync
