#!/bin/sh
#
# Starts Treadmill cleanup daemon.
# Runs as root with host principal creds.
#

# This service needs host tickets

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    cleanup watcher
