#!/bin/sh
#
# Starts Treadmill kernel watchdog.

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    kernel-watchdog \
        --kernel-watchdog-root {{ dir }}/kernel_watchdog \
        --reboot-script {{ dir }}/bin/reboot.sh
