#!/bin/sh
#
# Starts Treadmill cellapi.

RM={{ _alias.rm }}

${RM} -f /var/spool/cellapi.sock

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc \
    restapi \
        -s /tmp/cellapi.sock \
        --title 'Treadmill_Cell_API' \
        -m instance,app-monitor \
        --cors-origin='.*' \
        -a trusted
