#!/bin/sh
#
# Starts Treadmill cgroup management service
# Runs as root.
#

exec {{ treadmill_bin }} \
    sproc \
    --cell {{ cell }} \
    monitor node_services \
    --approot {{ dir }} \
    -S {{ dir }}/init
