#!/bin/sh
#
# Starts Treadmill node service monitor
# Runs as root.
#

exec {{ treadmill }}/bin/treadmill sproc --cgroup . \
    monitor node_services \
    --approot {{ dir }} \
    -S {{ dir }}/init
