#!/bin/sh
#
# Starts Treadmill event daemon.
# Runs as root with host principal creds.
#

CHOWN={{ _alias.chown }}

${CHOWN} -R {{ treadmillid }} /treadmill/appevents

exec \
    {{ treadmill_bin }} \
    sproc \
    appevents /treadmill/appevents
