#!/bin/sh
#
# Starts Treadmill metrics collection daemon.
#

# get data every 30 seconds
exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    metrics \
        --step 30 \
        --socket {{ dir }}/run/cgroup.sock
