#!/bin/sh
#
# Starts Treadmill Kafka instance
#

exec 2>&1

BROKER_PORT={{ me['kafka-client-port'] }}
if [ -z "$BROKER_PORT" ] || [ "$BROKER_PORT" == "None" ]
then
    echo "No Kafka client port set on this master and cell {{ cell }}"
    exec {{ sleep }} 60000
fi

echo "Running Kafka broker on port $BROKER_PORT"

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmllid }}
export JAVA_KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmllid }}

exec {{ s6 }}/bin/s6-setuidgid {{ treadmillid }} \
    {{ treadmill }}/bin/treadmill sproc --cell {{ cell }} kafka \
    --java-home {{ java_home }} \
    --broker-id {{ me.idx }} \
    --broker-port {{ me['kafka-client-port'] }}
