#!/bin/sh
#
# Starts Treadmill localdisk management service
# Runs as root.
#

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    service \
        --root-dir {{ dir }} \
    localdisk \
{%- if localdisk_img_location %}
        --img-location {{ localdisk_img_location }} \
{%- endif %}
{%- if localdisk_img_size %}
        --img-size {{ localdisk_img_size }} \
{%- endif %}
{%-if localdisk_block_dev %}
        --block-dev {{ localdisk_block_dev }} \
{%- endif %}
{%-if localdisk_vg_name %}
        --vg-name {{ localdisk_vg_name }} \
{%- endif %}
{%- if block_dev_configuration %}
        --block-dev-configuration {{ block_dev_configuration }} \
{%- endif %}
{%- if block_dev_read_bps %}
        --block-dev-read-bps {{ block_dev_read_bps }} \
{%- endif %}
{%- if block_dev_write_bps %}
        --block-dev-write-bps {{ block_dev_write_bps }} \
{%- endif %}
{%- if block_dev_read_iops %}
        --block-dev-read-iops {{ block_dev_read_iops }} \
{%- endif %}
{%- if block_dev_write_iops %}
        --block-dev-write-iops {{ block_dev_write_iops }} \
{%- endif %}
{%- if localdisk_default_read_bps %}
        --default-read-bps {{ localdisk_default_read_bps }} \
{%- endif %}
{%- if localdisk_default_write_bps %}
        --default-write-bps {{ localdisk_default_write_bps }} \
{%- endif %}
{%- if localdisk_default_read_iops %}
        --default-read-iops {{ localdisk_default_read_iops }} \
{%- endif %}
{%- if localdisk_default_write_iops %}
        --default-write-iops {{ localdisk_default_write_iops }} \
{%- endif %}
