#!/bin/sh

# Records time and exit code.
#

EXIT_CODE=$1
SIGNAL=$2

CAT=/bin/cat
MV=/bin/mv
TEMPFILE=$(mktemp)

echo $(date -u): rc=$EXIT_CODE signal=$SIGNAL >> finish.log
$CAT finish.log | tail -n 100 > $TEMPFILE
$MV $TEMPFILE finish.log
