#!/bin/sh
#
# Starts Treadmill cleanup daemon.
# Runs as root with host principal creds.
#

exec 2>&1

# This service needs host tickets
export KRB5CCNAME="FILE:$TREADMILL_HOST_TICKET"

exec {{ treadmill }}/bin/treadmill sproc --cgroup . \
    version_monitor -- {{ dir }}/bin/reset.sh
