#!/bin/sh
#
# Starts Treadmill reboot monitor.
# Runs as root.
#

exec 2>&1

# This service needs host tickets
export KRB5CCNAME="FILE:$TREADMILL_HOST_TICKET"

exec {{ treadmill }} sproc --cgroup . \
    reboot-monitor -- {{ dir }}/bin/reboot.sh
