#!/bin/sh
#
# Starts alert receiver service that forwards messages to netcool
#

exec 2>&1

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmillid }}
export PEX_ROOT=/tmp/.pex_{{ treadmillid }}

exec                                                                        \
    {{ s6 }}/bin/s6-setuidgid {{ treadmillid }}                             \
    {{ treadmill_bin }} sproc                                               \
        alerts receive
