#!/bin/sh
#
# Script to start the DNAT watcher in the same pid/mount namespace as treamill
# node.
# Runs as root
#

# FIXME: The location of all this dirs should be in a config somewhere
exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    firewall watcher \
        --root-dir {{ dir }}
