#!/bin/sh
#
# Starts Treadmill running container monitor
# Runs as root.
#

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    monitor containers \
        --approot {{ dir }} \
        -S {{ dir }}/running
