#!/bin/sh
#
# Takes broken nodes out of rotation.
#

exec 2>&1

OUTDIR=/treadmill/data/checkout
{{ chown }} -R nobody $OUTDIR

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmillid }}

{{ mkdir }} -p $OUTDIR

exec {{ treadmill }}/bin/treadmill sproc checkout \
      --outdir $OUTDIR \
      --port 0 \
      --plugin treadmill.plugins.sproc.checkout \
      api zk sysapps servers ldap dns capacity
