#!/bin/sh
#
# Starts Treadmill network management service
# Runs as root.
#

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    service \
        --root-dir {{ dir }} \
    network \
{%- if network_device %}
        --ext-device {{ network_device }} \
{%- endif %}
{%- if network_ip%}
        --ext-ip {{ network_ip}} \
{%- endif %}
{%- if network_mtu %}
        --ext-mtu {{ network_mtu }} \
{%- endif %}
{%-if network_speed %}
        --ext-speed {{ network_speed }} \
{%- endif %}
