#!/bin/sh
#
# Starts rrdcached daemon.
#

RM={{ _alias.rm }}
CHOWN={{ _alias.chown }}
MKDIR={{ _alias.mkdir }}

${RM} /tmp/treadmill.rrd.pid
${RM} /tmp/treadmill.rrd

${MKDIR} -p {{ dir }}/metrics/apps
${MKDIR} -p {{ dir }}/metrics/core

${CHOWN} -R nobody {{ dir }}/metrics

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    exec -- \
        {{ _alias.s6_setuidgid }} nobody \
        {{ rrdcached }} \
            -g \
            -l unix:/tmp/treadmill.rrd \
            -p /tmp/treadmill.rrd.pid
