#!/bin/sh
#
# Starts Treadmill nodeinfo webserver process.
# Runs as root with host principal creds.
#

# This service needs host tickets

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    nodeinfo \
        --register \
        --cors-origin='.*' \
        -m local
