#!/bin/sh

exec 2>&1

DIR={{ dir }}
DIRNAME={{ dirname }}
GIT={{ git }}
MKDIR={{ mkdir }}
ENV={{ env }}
URI={{ uri }}

BACKUP_DIR=/v/region/local/appl/cloud/treadmill/data/$ENV/ldap-backup
$MKDIR -pv $BACKUP_DIR

GIT_BIN_DIR=$($DIRNAME $GIT)

PATH=${GIT_BIN_DIR}:$PATH

exec {{ treadmill }}/bin/treadmill sproc ldap-backup \
    --uri $URI --backup-dir $BACKUP_DIR
