#!/bin/sh

# Records time and exit code.
#

EXIT_CODE=$1
SIGNAL=$2

MV=/bin/mv
CHMOD=/bin/chmod
TEMPFILE=$(mktemp)

echo $(date -u): rc=$EXIT_CODE signal=$SIGNAL >> finish.log
tail -n 100 finish.log > $TEMPFILE
$MV $TEMPFILE finish.log
$CHMOD 644 finish.log
