#!/bin/sh
#
# Starts Treadmill metrics collection daemon.
#

# get data every 30 seconds
exec {{ treadmill }}/bin/treadmill sproc --cgroup . metrics --step 30 \
    --socket {{ dir }}/var/run/cgroup.sock
