#!/bin/sh
#
# Starts syncronization between cell Zookeeper and configuration db.
#

exec 2>&1

export PEX_ROOT=/tmp/.pex_{{ treadmillid }}
export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmillid }}
exec {{ s6 }}/bin/s6-setuidgid {{ treadmillid }} \
    {{ treadmill }}/bin/treadmill sproc --cell {{ cell }} trace cleanup
