#!/bin/sh
#
# Starts Treadmill event daemon.
# Runs as root with host principal creds.
#

# This service needs host tickets

exec \
    {{ treadmill_bin }} \
    sproc --cgroup . \
    appevents \
        {{ dir }}/appevents
