#!/bin/sh
#
# Starts Treadmill network management service
# Runs as root.
#

exec 2>&1

exec {{ treadmill }}/bin/treadmill sproc --cgroup . \
    service --root-dir {{ dir }} network \
{%- if network_device %}
    --device {{ network_device }} \
{%- endif %}
{%- if network_mtu %}
    --mtu {{ network_mtu }} \
{%- endif %}
{%-if network_speed %}
    --speed {{ network_speed }} \
{%- endif %}
