#!/bin/sh
#
# Starts uds server that will take input and touch a file in the correct
# appevents directory
#

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    exec -- \
    {{ _alias.s6_ipcserver }} {{ dir }}/ctl/appevents \
    {{ _alias.s6_ipcserver_access }} -i ./data/access \
    ./data/write_appevents.sh
