#!/bin/sh

# Script to start the synchronization job that updates the set of Treadmill
# nodes for use by the firewall.
# Runs as root with host principal creds.
#

exec 2>&1

# This service needs host tickets
export KRB5CCNAME="FILE:$TREADMILL_HOST_TICKET"

exec {{ treadmill }}/bin/treadmill sproc --cgroup . firewall node_sync
