#!/bin/sh
#
# Starts Treadmill master scheduler process.
# Runs as {{ treadmillid }} proid
#

exec 2>&1

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmillid }}
export PEX_ROOT=/tmp/.pex_{{ treadmillid }}
exec {{ s6 }}/bin/s6-setuidgid {{ treadmillid }} {{ treadmill }} sproc scheduler /treadmill/appevents
