#!/bin/sh
#
# Starts Treadmill master scheduler process.
# Runs as {{ treadmillid }} proid
#

exec 2>&1

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmillid }}
exec {{ s6 }}/bin/s6-setuidgid {{ treadmillid }} \
    {{ treadmill }}/bin/treadmill sproc scheduler /treadmill/appevents
