#!/bin/sh
#
# Starts zookeeper.
# Runs as {{ treadmillid }} proid.
#

exec 2>&1

SCRIPT_NAME=${0##*/}
SCRIPT_DIR=${0%/$SCRIPT_NAME}

KUULA={{ kuula }}
ECHO={{ echo }}

# Fix kuula bug.
#
# Kuula cleanup_environment sets SIDE to empty on Zephyr/aq hosts, which is
# invalid value.
#
# Unsetting SIDE fixes the problem.
unset SIDE

$ECHO "" >> ${SCRIPT_DIR}/zk.yml
${KUULA} rebuild ${SCRIPT_DIR}/zk.yml

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmllid }}

exec {{ s6 }}/bin/s6-setuidgid {{ treadmillid }} \
    ${KUULA} start ${SCRIPT_DIR}/zk.yml
