#!/bin/sh
#
# Starts Treadmill master scheduler process.
# Runs as {{ treadmillid }} proid
#

# XXX: Should be in aliases
CHKSUM="/usr/bin/md5sum"
READLINK="/usr/bin/readlink"


# Figure out the TZ value

if [ -n "$TZ" ]; then
    echo "Using system TZ"
elif [ -f /etc/timezone ]; then
  TZ=$(cat /etc/timezone)
elif [ -h /etc/localtime ]; then
  TZ=$(${READLINK} /etc/localtime | sed -e 's|/usr/share/zoneinfo/||')
else
  localtime_chksum=$(${CHKSUM} /etc/localtime | cut -d' ' -f1)
  TZ=$(find /usr/share/zoneinfo/ -type f | \
        xargs ${CHKSUM} | \
        grep "^${localtime_chksum}" | \
        head -n 1 | \
        sed -e 's|.* /usr/share/zoneinfo/||')
fi

echo "TZ: $TZ"
export TZ

exec \
    {{ treadmill_bin }} \
    sproc \
    cron
