#!/bin/sh
#
# Starts Treadmill cleanup daemon.
# Runs as root with host principal creds.
#

# This service needs host tickets

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    version-monitor -- \
        {{ dir }}/bin/reset.sh
