#!/bin/sh
#
# Starts Treadmill master scheduler process.
# Runs as {{ treadmillid }} proid
#

exec 2>&1

export PEX_ROOT=/tmp/.pex_{{ treadmillid }}

export KRB5CCNAME=FILE:/var/spool/tickets/{{ treadmillid }}
export TZ=$(find /usr/share/zoneinfo/ -type f| xargs md5sum | grep $(md5sum \
    /etc/localtime | cut -d' ' -f1) | head -1 | cut -d' ' -f3 | sed -e \
    's/\/usr\/share\/zoneinfo\///')

echo "TZ: $TZ"

exec {{ s6 }}/bin/s6-setuidgid {{ treadmillid }} \
    {{ treadmill }}/bin/treadmill sproc cron
