#!/bin/sh
#
# Starts Treadmill cgroup-info webserver process.
# Runs as root with host principal creds.
#

# refresh data every 30 seconds
exec {{ treadmill }}/bin/treadmill sproc --cgroup . \
    cgroup-server --cors-origin='.*' --socket {{ dir }}/var/run/cgroup.sock \
    --interval 30
