#!/bin/sh
#
# Starts Treadmill node service monitor
# Runs as root.
#

exec \
    {{ treadmill }}/bin/treadmill34 \
    sproc --cgroup . \
    monitor node_services \
        --approot {{ dir }} \
        -S {{ dir }}/init \
        -S {{ dir }}/init1
